### ISSUE TITLE
[Request] Sony SKX format (MLB 2004 [PS2], Syphon Filter PS2/PSP games, etc)

### ISSUE THREAD

**Issue by AnonRunzes** [vgmstream/vgmstream#1596] opened 2024-09-14 14:17 UTC
> i'm just leaving this here before i forget.
> 
> i came across some PS2 and PSP games from first-party Sony games that used this weird "SKX" format which is essentially a container set that consists of "bigfiles" containing streamed sounds alongside some "companion files" that hold essential information for those files so they can be played in-game.
> 
> as i uncover more and more of them that use this format, i believe it's best to leave this issue open for now. i have a hunch that there are some first-party PS3 games that use this format.
> 
> anyway, here are the samples. 
[skx[mlb_2004][ps2].7z](https://krakenfiles.com/view/VoWv3Zujgs/file.html) 
[skx[mlb_2005][ps2].7z](https://krakenfiles.com/view/amd8vQ3MFK/file.html) 
[skx[mlb-2006][ps2].7z](https://krakenfiles.com/view/ReTkExaqn2/file.html) 
[skx[mlb][psp].7z](https://krakenfiles.com/view/QdYwNvziLy/file.html) 
[skx[syphon-filter-dark-mirror][ps2].7z](https://krakenfiles.com/view/wDt9mxNkGP/file.html) 
[skx[syphon-filter-dark-mirror][psp].7z](https://krakenfiles.com/view/NY2991vvhC/file.html) 
[skx[syphon-filter-logan's-shadow][ps2].7z](https://krakenfiles.com/view/HezBHua9mS/file.html) 
[skx[syphon-filter-logan's-shadow][psp].7z](https://krakenfiles.com/view/3xvi8pjaiG/file.html)

**Comment by bnnm** [comment] 2024-09-15 22:25
Dupe of #1198

**Closed by bnnm** 2024-09-15 22:25 UTC
Labels: enhancement
